/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringDemo */

#ifndef _Included_StringDemo
#define _Included_StringDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringDemo
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StringDemo_getLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
